### ISSUE TITLE
Refine the TrekTours projects deployment scripts

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/CloudDeploy#1]
@damirius 

In https://github.com/Puzzlout/CloudDeploy/tree/master/Projects/TrekTours, you have the scripts to use. The C9 workspace has already this repo cloned.

Any updates to the scripts will need to be committed under this issue. Thanks.

PS: you can commit to the master branch.

Related to:
- https://github.com/Puzzlout/TrekToursApi/issues/22
- https://github.com/Puzzlout/TrekToursFlyer/issues/7

**Comment by damirius** [comment]
@WebDevJL 

Install/refresh scripts were mostly OK.
Other than that most of the problems were caused by php version. First off phpbrew must install new versions with +apxs2 argument so that it installs apache extensions also not only cli. Also we needed to add +mysql so that it installs mysql driver needed. Other than that I've added to deploy script installation of some curl package and after phpbrew build I've added curl as extension too.
Phpbrew installs new module loading configs for apache2 automatically, but it doesn't remove old ones, so that has to be done manually if they are preinstalled there.
So anyways most of the stuff that has to do with install/refresh scripts for our projects is already done and it works great, other stuff that depends on system configuration is problematic. It should work now so whenever you are ready you can start the server and check everything out.
When you do go to /api/web/doc to see if documentation is generated for the API project.
If it is you can go to /public/web/en/contact to create new CRI using contact form, that should work too if everything is OK. I've tested it and it created new CRI entry.
To double check that go to /public/web/admin/customerinforequests it will display login form, use `admin` as user and `hWhC5YM5` as password. Please note that in install script I ran create user with admin:admin user/pass combo, so when installing it all through the script login will be admin:admin.
If you get logged in our authorization bridge also work and you should see customerinforequest(s) you made over contact form.

Ask me if there is problem with anything

**Comment by WebDevJL** [comment]
@damirius ok great. Have you listed the commands you run for the server
setup? What I'd like to do next is to do it from a new workspace and check
if everything is working.

Then we will add some stuff about creating tags on GitHub and pulling just
a given tag on master branch.

Thank you for the effort so far.

## 

Jérémie Litzler

**Comment by damirius** [comment]
@WebDevJL 

I think everything should be in deploy.sh script. Only thing left out is removal of php libraries. Now that depends on apache setup. If c9 workspace comes with preinstalled apache2 php modules they have to be removed.
So few commands I can think from my head, just want your feedback on this.
`cp /etc/apache2/mods-available/php5.conf /etc/apache2/mods-available/php7.conf`
`ln -s /etc/apache2/mods-available/php7.conf /etc/apache2/mods-enabled/php7.conf`
`rm /etc/apache2/mods-enabled/php5.load`

Now that depends if apache2 is installed like that with php5, if not then there's no use for that.

**Comment by WebDevJL** [comment]
@damirius Just a quick one: AWESOMELY done! Everything work on the flyer
and api!

I will check the scripts and replicate the procedure soon. :+1:

**Comment by WebDevJL** [comment]
@damirius More work for you. On the C9, can you create a new workspace using the repo https://github.com/Puzzlout/TrekToursInstaller.git in the workspace creation form.

Then run setup-server.sh and try to figure out why phpbrew can't install php version 7.0.1 in `deploy/php-upgrade.sh 7.0.3`. I see some problem with apxs...

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

OK, I've added install command for apache2 dev tools which are required for this to work with apxs2 option. Also I've added removal of php5 module automatically, there were few more things I had to deal with. I hope it will work like this now.

Also please note that on that trektoursinstaller repo you need to remove api/deploy/public directories if you want to use `mv` command to rename git projects, since if you have existing directories git projects will be moved inside those dirs instead of renamed.

**Comment by WebDevJL** [comment]
@damirius Yes, I saw the folders. They are removed.

Other than that, it seems we have a problem with the parameter "gmail":
![screen shot 2016-07-10 at 18 34 52](https://cloud.githubusercontent.com/assets/3506074/16714745/28c02db6-46cd-11e6-9e4d-a5b04d805295.png)
Below is the full logs:
[install-c9.log.zip](https://github.com/Puzzlout/CloudDeploy/files/356100/install-c9.log.zip)

Do you know what it is about?

**Comment by WebDevJL** [comment]
@damirius  PS: it happened after the prompts for the parameters

**Comment by WebDevJL** [comment]
@damirius I think it was the password of the email user... Now, regarding the databases, do we need to create them before running the script ?

**Comment by damirius** [comment]
@WebDevJL 

Hm, I think that % is a special sign in yaml. So if we have some of those special characters we must use quotes around the pass.

We can create the db before, but there's no need, clear cache will require database connection for some reason and it will display an error, but there's no actual need for db connection since we don't actually have cache when we pull the repo for the first time. DB will be created afterwards automatically but after composer install of course, since we need to create that bin/console script first through it

**Comment by WebDevJL** [comment]
@damirius yes, it was the "%"... So it seems that the php 7 upgrade is still failing... Any ideas?

```
<=====================================================>
phpbrew - 1.22.5
cliframework core: 2.5.4
Downloading https://secure.php.net/releases/index.php?json&version=7&max=100 via curl extension
[==================================================================] 6.12/6.12KB 100%
Downloading https://secure.php.net/releases/index.php?json&version=5&max=100 via curl extension
===> phpbrew will now build 7.0.1
---> Parsing variants from command arguments '+default+apxs2+mysql'
===> Loading and resolving variants...
Creating directory /home/ubuntu/.phpbrew/variants
Downloading http://www.php.net/get/php-7.0.1.tar.bz2/from/this/mirror via curl extension
Redirecting to http://nl1.php.net/distributions/php-7.0.1.tar.bz2
[==================================================================] 13.34/13.34MB 100%
http://www.php.net/get/php-7.0.1.tar.bz2/from/this/mirror => /home/ubuntu/.phpbrew/distfiles/php-7.0.1.tar.bz2
===> Extracting /home/ubuntu/.phpbrew/distfiles/php-7.0.1.tar.bz2 to /home/ubuntu/.phpbrew/build/tmp.1468213377/php-7.0.1
===> Moving /home/ubuntu/.phpbrew/build/tmp.1468213377/php-7.0.1 to /home/ubuntu/.phpbrew/build/php-7.0.1
Source Directory: /home/ubuntu/.phpbrew/build/php-7.0.1
Writing variant info to /home/ubuntu/.phpbrew/php/php-7.0.1/phpbrew.variants
Found apxs2 binary: /usr/bin/apxs
===> Checking patches...
Checking patch for replace apache php module name with custom version name
30 changes patched.
Enabled variants: [apxs2, mysql, xml, opcache, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, mcrypt, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
===> Configuring 7.0.1...


Use tail command to see what's going on:
   $ tail -F /home/ubuntu/.phpbrew/build/php-7.0.1/build.log


./configure '--cache-file='\''/home/ubuntu/.phpbrew/cache/config.cache'\''' '--prefix=/home/ubuntu/.phpbrew/php/php-7.0.1' '--with-config-file-path=/home/ubuntu/.phpbrew/php/php-7.0.1/etc' '--with-config-file-scan-dir=/home/ubuntu/.phpbrew/php/php-7.0.1/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-apxs2=/usr/bin/apxs2' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-opcache' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--with-mcrypt=/usr' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-pdo' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip' '--with-pear=/home/ubuntu/.phpbrew/php/php-7.0.1/lib/php' >> /home/ubuntu/.phpbrew/build/php-7.0.1/build.log 2>&1
===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
===> Building...
make >> /home/ubuntu/.phpbrew/build/php-7.0.1/build.log 2>&1
Build finished: 7.9 minutes.
Installing...
Error: Install failed:
The last 5 lines in the log file:
ERROR: Failed to create marker '/var/lib/apache2/module/enabled_by_admin/php7'!

To activate the new configuration, you need to run:

  service apache2 restart

'a2enmod php7' failed

make: *** [install-sapi] Error 25

Please checkout the build log file for more details:
         tail /home/ubuntu/.phpbrew/build/php-7.0.1/build.log
deploy/php-upgrade.sh: 14: deploy/php-upgrade.sh: source: not found
Invalid argument 7.0.1
Invalid argument 7.0.1
Error: PHPBREW_PHP environment variable is not defined.
  This extension command requires you specify a PHP version from your build list.
  And it looks like you haven't switched to a version from the builds that were built with PHPBrew.
Suggestion: Please install at least one PHP with your prefered version and switch to it.
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
Installing the applications
Already up-to-date.
Run composer...
```

**Comment by damirius** [comment]
@WebDevJL 

it's problem with permission again. Try running `sudo -R chmod oag+rw /var/lib/apache2/module/enabled_by_admin`
If that does work we can add that command too before `phpbrew install` command

**Comment by WebDevJL** [comment]
@damirius I'll try that and let you know.

**Comment by WebDevJL** [comment]
@damirius I need you again on this. Please create a new workspace on your C9 account and clone https://github.com/Puzzlout/TrekToursInstaller.git and run setup-server.sh.

I have excluded the php upgrade because it doesn't work... But it would be nice to make it work. For now, we need to the applications to work.

With setup-server script, I got the API and Flyer to run ok but I can't login to the admin. I tried "admin / admin" but I have errors:
![image](https://cloud.githubusercontent.com/assets/3506074/16757907/004ab962-480f-11e6-832f-894086a2f8bd.png)

Please make sure the install is done all through the script. I'd like to leave no manual action outside of the script setup-server.

Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I'm on it. That error means that apache isn't running php7 but some lesser version.

**Comment by WebDevJL** [comment]
@damirius So you need tackle that PHP7 upgrade issue... Let me know if it
is too complicated because we are dealing with a temporary hosting. Thanks.

**Comment by damirius** [comment]
@WebDevJL 

I think this is it. I've ran just `bash setup-server.sh` and everything is working. Man there sure was lot of stuff going on with phpbrew installer...

**Comment by WebDevJL** [comment]
@damirius phpbrew is great but hard to handle! I will test all this. Thanks
again for your responsiveness!

**Comment by WebDevJL** [comment]
@damirius You nailed it! It is working from start to end with no fault!
Well done and thank you for the great job. The client will be happy.

Now, I will need to test the update scripts for but since the hassle was
the PHP version upgrade, that shouldn't be a problem to perform.

**Comment by damirius** [comment]
@WebDevJL 

Great!
I don't think update scripts will make some problems, of course you can never know for sure. Tell me if you notice something unusual with them so we can see if they can be easily fixed.
